global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "main-server"
    static_configs:
      - targets: ["main-server:3000"]

  - job_name: "consumer"
    static_configs:
      - targets: ["consumer:3001"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
